# Generated by Django 5.2.14 on 2026-07-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='V1', max_length=50)),
                ('units_per_outer', models.PositiveIntegerField(default=0)),
                ('ti', models.PositiveIntegerField(default=0)),
                ('hi', models.PositiveIntegerField(default=0)),
                ('tpq_cases', models.PositiveIntegerField(default=0)),
                ('tpq_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_sku', models.CharField(blank=True, max_length=100)),
                ('component_name', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('units_per_piece', models.CharField(blank=True, max_length=100)),
                ('units_per_outer', models.CharField(blank=True, max_length=100)),
                ('packaging_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='apps.packagingspecification')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional product notes')),
                ('transaction', models.CharField(blank=True, choices=[('machine', 'Machine Packed'), ('hand', 'Hand Packed'), ('mixed', 'Machine + Hand Packed'), ('other', 'Other')], max_length=20)),
                ('inner_barcode', models.CharField(blank=True, max_length=100)),
                ('outer_barcode', models.CharField(blank=True, max_length=100)),
                ('pallet_configuration', models.CharField(blank=True, max_length=100)),
                ('date_set_up', models.DateField(blank=True, null=True)),
                ('suspend_record', models.BooleanField(default=False)),
                ('issue', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.customer')),
            ],
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_specifications', to='apps.product'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='packing_spec', max_length=30)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='packaging_specs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apps.product')),
            ],
        ),
        migrations.AddField(
            model_name='packagingspecification',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.uploadedfile'),
        ),
        migrations.CreateModel(
            name='PackingProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('packaging_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_process_steps', to='apps.packagingspecification')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('packaging_specification', 'step_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='packagingspecification',
            unique_together={('product', 'version')},
        ),
    ]
