# Generated by Django 5.2.14 on 2026-08-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worksheet_data', models.JSONField(blank=True, default=dict)),
                ('traceability_data', models.JSONField(blank=True, default=dict)),
                ('reject_report_data', models.JSONField(blank=True, default=dict)),
                ('date_coding_data', models.JSONField(blank=True, default=dict)),
                ('stocktake_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpacks', to='apps.product')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('product', 'date'), name='unique_product_workpack_date')],
            },
        ),
    ]
